### ISSUE TITLE
Some prompts remove last line from command output

### ISSUE THREAD

**Issue by ickerwx** [sorin-ionescu/prezto#1557] opened 2018-03-07 14:42 UTC
### Description
I just noticed this again, but it has happened in the past as well: I am inside a directory and run `cat` on a file:
```
(using a fancy prompt like agnoster)$ cat file
line 1
(fancy prompt again)
```
Now, if I run `cat` again using a less fancy prompt, I get this:
```
(less fancy prompt like minimal)$ cat file
line 1
line 2
(less fancy prompt again)
```
### Expected behavior
I expect to see all lines of the file.

### Actual behavior
The last line is missing from the output
![2018-03-07-152628_696x200_scrot](https://user-images.githubusercontent.com/7716530/37098291-d95425ec-221d-11e8-9336-8f5235b69aa3.png)
It looks like some of the prompts have trouble working with output that does not end with a newline character.

### Steps to Reproduce
1. Create a file containing multiple lines of text, make sure that the last line does **not have a newline character at the end**
2. Switch to a prompt like agnoster, powerline or fade (I did not test all prompts!)
3. run `cat` on the file and see that the last line is not printed

### Versions
  - Prezto commit: b3c27bb
  - ZSH version: zsh 5.4.2
  - OS information: Arch Linux 4.15.5-1-ARCH

**Comment by belak** [comment] 2018-03-07 16:18
I'm guessing these prompts don't specify prompt_sp.

Here's an example fixing agnoster: https://github.com/agnoster/agnoster-zsh-theme/pull/46

I'll take a closer look when I'm at an actual computer and not on my phone but I'd be willing to bet this is it ;)

**Comment by ickerwx** [comment] 2018-03-09 13:06
I can confirm that the problem is gone when I apply the fix you mentioned.

**Comment by belak** [comment] 2018-03-10 00:51
I'm going to close this for now as it's a duplicate of https://github.com/sorin-ionescu/prezto/issues/1425 and there's a workaround. Thanks for reporting!

**Closed by belak** 2018-03-10 00:51 UTC
