### ISSUE TITLE
Error when using in a multi user setup

### ISSUE THREAD

**Issue by akshayrawat** [sorin-ionescu/prezto#1199] opened 2016-09-24 19:18 UTC
I get this error when using prezto from a second user (where the first user also uses prezto) on MacOS.

> prompt_sorin_precmd_async:4: permission denied: /tmp/zsh-prompt_sorin_data

Doing a `chmod a+r+w` for it creates the same problem for the other user.

prezto version: latest as of now
zsh 5.2 (x86_64-apple-darwin15.4.0)

**Comment by ezintz** [comment] 2016-09-25 13:36
It seems like this line https://github.com/sorin-ionescu/prezto/blob/4f19700919c8ebbaf75755fc0d03716d13183f49/runcoms/zprofile#L71 is responsible for creating the directory where your prompt, `sorin` is trying to save data to.

Since the directory is created with 700 you can change it for example to 777 to allow everyone to write to it. I am not sure if this is correct, what if multiple users are logged in? From my understanding each user is overwriting the data of the other one, if all are using the same prompt.

I would change the prompt setup to be unique for each user at https://github.com/sorin-ionescu/prezto/blob/4f19700919c8ebbaf75755fc0d03716d13183f49/modules/prompt/functions/prompt_sorin_setup#L101.

**Comment by jlax47** [comment] 2016-10-12 04:24
@akshayrawat I think there might be something wrong with your system. By default, osx creates a user specific temp directory. You should not be getting any conflicts because $TMPDIR should already be set and be specific to you.

Also the fact that the directory that you are trying to create is: `/tmp/zsh-prompt_sorin_data` tells me that `$TMPDIR` is not set or doesn't exist and the variable `$LOGNAME` is empty.

I don't know exactly what's going on with your system, but it should be a fairly easy fix. Edit the file: `.zprezto/runcoms/zprofile` and change lines 70-71 from:

```
if [[ ! -d "$TMPDIR" ]]; then
  export TMPDIR="/tmp/$LOGNAME"
  mkdir -p -m 700 "$TMPDIR"
fi
```

to:

```
if [[ ! -d "$TMPDIR" ]]; then
  export TMPDIR="$(mktemp -d)"
fi
```

This will create a per user temporary directory with the correct permissions which should prevent the problem you are seeing (and others you haven't seen yet).

**Comment by jlax47** [comment] 2016-10-12 05:10
#1209 - Not sure if this will get merged or not, but I think it's a reasonable fix.

**Comment by paulmelnikow** [comment] 2017-03-02 14:18
Hey @donpatrice, #1209 was merged into  [zsh-users/prezto](https://github.com/zsh-users/prezto), the community fork of this repo. zsh-users is an organization dedicated to host Zsh community projects and therefore became the rational home for a community maintained version of prezto. See #1239 for more information on the fork.

This is [the commit](https://github.com/zsh-users/prezto/commit/436a7f941ecb07909c112bb5a96a1bbcc4f6f13c).

You may want to migrate over. There are some [upgrade instructions](https://github.com/zsh-users/prezto/pull/33/files#diff-04c6e90faac2675aa89e2176d2eec7d8), soon to be merged.

**Comment by donpatrice** [comment] 2017-03-03 07:56
Thank you @paulmelnikow very much for the hint. The commit mentioned does not work for me, I will open an issue on zsh-users.

**Comment by belak** [comment] 2017-04-05 18:39
The fix was merged yesterday, so I'm closing this issue now.

**Comment by paulmelnikow** [comment] 2017-04-05 21:03
So, as it turns out, the fix in #1209 only fixed the issue for login shells.

There are a couple ways this could be fixed for non-login shells: see https://github.com/zsh-users/prezto/issues/35#issuecomment-285049224 and https://github.com/zsh-users/prezto/issues/35#issuecomment-285062100.

@belak Would you like to reopen this, so we can finish up that discussion here?

**Comment by belak** [comment] 2017-04-05 21:05
Sure, makes sense. Thanks for following up.

**Comment by belak** [comment] 2017-04-05 21:06
I think the best method may be to set TMPPREFIX in init.zsh, as that would ensure it's handled properly.

**Comment by paulmelnikow** [comment] 2017-04-05 21:16
That would fix TMPPREFIX, which would be good as a minimum since prezto itself depends on it. (Though TMPPREFIX is itself a zsh thing.)

That said, the rest of the `.zprofile` handling seems similarly broken in non-login shells. Can you think of a way to fix [the test in .zshenv](https://github.com/sorin-ionescu/prezto/blob/master/runcoms/zshenv#L9)?

**Comment by belak** [comment] 2017-04-05 22:45
I'm not sure what the best way to handle this would be... I guess this is a bit more complicated than first glance.

**Comment by binarykitchen** [comment] 2017-06-18 00:25
so, what's the official fix? it still happens for me on latest master

**Comment by belak** [comment] 2017-06-19 08:02
I don't know if there *is* a "correct" fix for the runcoms. I haven't actually used them in a while, so I'm not the best person to ask about those.

That being said, the sorin prompt should be fixed, as https://github.com/sorin-ionescu/prezto/commit/2f20a80f7255bffcf878de70192f6df126c6069f ensured a unique tmp file is created for each running process and https://github.com/sorin-ionescu/prezto/commit/a0541ce7a5f3ee5b0d869f1cd2b5546558e3750d ensured that we fall back to /tmp if TMPDIR isn't set.

If you're having similar issues with other parts of the code, or you have more info I can use to reproduce this, I'd be happy to look into it further.

**Comment by binarykitchen** [comment] 2017-06-19 21:56
ok, will `git pull` once those two commits are merged @belak

**Comment by belak** [comment] 2017-06-19 22:03
Those commits were merged about a week ago.

**Comment by binarykitchen** [comment] 2017-06-19 22:09
hmmm, but they still happen

```
nodejs@binarykitchen ~/.zprezto ❯❯❯ git pull
remote: Counting objects: 9, done.
remote: Total 9 (delta 3), reused 3 (delta 3), pack-reused 6
Unpacking objects: 100% (9/9), done.
From https://github.com/sorin-ionescu/prezto
   a0541ce..d9a1380  master     -> origin/master
Updating e606b09..d9a1380
nodejs@binarykitchen ~/.zprezto ❯❯❯ prompt_sorin_precmd_async:4: permission denied: /tmp/zsh-prompt_sorin_data                                               ⏎
nodejs@binarykitchen ~/.zprezto ❯❯❯ zsh                                                                                                                      ⏎
nodejs@binarykitchen ~/.zprezto ❯❯❯ prompt_sorin_precmd_async:4: permission denied: /tmp/zsh-prompt_sorin_data
```

**Comment by belak** [comment] 2017-06-19 22:10
After pulling did you try in the current shell or a new shell? The current shell would have the old code loaded.

**Comment by binarykitchen** [comment] 2017-06-19 22:11
in a new shell of course, that's why i entered `zsh` inbetween, see above

and no idea who/where `/tmp/zsh-prompt_sorin_data` is being set

**Comment by belak** [comment] 2017-06-19 22:14
Ah, I didn't see the new shell call. Maybe it's loading from a different location than you think it is. `ag prompt_sorin_data` gives zero results against the current commit on master.

**Comment by binarykitchen** [comment] 2017-06-19 22:23
ok - all i want to know is how to fix this? :)

**Comment by belak** [comment] 2017-06-19 22:28
It should be fixed on master, as I mentioned... but for whatever reason, however you're loading prezto isn't picking up the new version... which leads me to believe that prezto may be cloned to multiple locations on your system and the one which is actually being used has not been updated.

Are your dotfiles posted anywhere? I'd be happy to take a look to see if I can spot anything.

**Comment by binarykitchen** [comment] 2017-06-19 22:30
well, the dotfiles are exactly the defaults you provide

```
lrwxrwxrwx    1 nodejs nodejs   36 Nov 25  2016 .zlogin -> /home/nodejs/.zprezto/runcoms/zlogin
lrwxrwxrwx    1 nodejs nodejs   37 Nov 25  2016 .zlogout -> /home/nodejs/.zprezto/runcoms/zlogout
lrwxrwxrwx    1 nodejs nodejs   39 Nov 25  2016 .zpreztorc -> /home/nodejs/.zprezto/runcoms/zpreztorc
lrwxrwxrwx    1 nodejs nodejs   38 Nov 25  2016 .zprofile -> /home/nodejs/.zprezto/runcoms/zprofile
lrwxrwxrwx    1 nodejs nodejs   36 Nov 25  2016 .zshenv -> /home/nodejs/.zprezto/runcoms/zshenv
-rw-------    1 nodejs nodejs  404 Nov 25  2016 .zsh_history
lrwxrwxrwx    1 nodejs nodejs   35 Nov 25  2016 .zshrc -> /home/nodejs/.zprezto/runcoms/zshrc
```

**Comment by belak** [comment] 2017-06-19 22:37
This is what I see with the default setup:

```
[belak@torbjorn ~]$ zsh
~ ❯❯❯ cd .zprezto
~/.zprezto ❯❯❯ git rev-parse HEAD
d9a1380263bbeb27a9ed91b79e04e99b65760535
~/.zprezto ❯❯❯ cd
~ ❯❯❯ ls /tmp/sorin*
/tmp/sorin-prompt-async-HSi7MuXutW
~ ❯❯❯ ls /tmp/zsh*
zsh: no matches found: /tmp/zsh*
```

**Comment by belak** [comment] 2017-06-19 22:46
This might be a silly question, but are you on the master branch, or do you have another branch checked out? Also, are you using a custom fork? Your `git pull` log said `Updating e606b09..d9a1380` but `e606b09` doesn't appear to exist in the main prezto repo.

**Comment by binarykitchen** [comment] 2017-06-19 22:49
aaaaaaaaahhhh, finally solved it myself. i had a little git mess, ignored some files. not reverted that and pulled all over again incl submodules. all good now :)

thanks for your help dude!

**Comment by belak** [comment] 2017-06-19 22:51
Glad you got it figured out! And it sounds like this fixed the error for you, so I'm closing this for now. :D 

This should be solved, but if anyone runs into this issue please let me know and I can repopen it.

**Closed by belak** 2017-06-19 22:51 UTC
Labels: Bug
