### ISSUE TITLE
Updating issues

### ISSUE THREAD

**Issue by SanketDG** [sorin-ionescu/prezto#1602] opened 2018-07-09 14:26 UTC
### Description

When I want to update prezto, I am presented with conflicts. I know this is because I made all the changes in $ZPREZTODIR itself.

How can I fix this, so that I can keep my own config alongside an updated prezto?

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

### Versions

  - Prezto commit: 282b478
  - ZSH version: 5.5.1
  - OS information: Fedora 28

**Comment by johnpneumann** [comment] 2018-07-18 13:11
Possible duplicate of #1535

**Comment by ezintz** [comment] 2018-09-15 17:32
Not sure if this is possible since you are applying changes to the framework itself (thats how version control works, no? I mean you are mainting more or less your own fork).

However, If you are just modyfing configuration files e.g. `.zshrc` you can create a copy of the original one instead of symlinking it and afterwards you can make as many changes as you want without facing any conflicts. You might need to be careful in case the any of the runcom files changed, which actually is not happening that often (I think)

If anyone has better ideas, please let me know (;

**Closed as completed** 2018-09-28 21:26 UTC
Labels: Duplicate
