### ISSUE TITLE
Forced to have git aliases

### ISSUE THREAD

**Issue by posva** [sorin-ionescu/prezto#947] opened 2015-08-09 09:51 UTC
Hello,

When using the git plugin to have git information in prompt there's no way to skip alias definition. Can we add an option that can be enabled to skip aliases ?

This option could also be used to skip alias definition in other plugins.

**Comment by sorin-ionescu** [comment] 2015-08-30 18:44
Duplicate of #310.

**Closed by sorin-ionescu** 2015-08-30 18:44 UTC
Labels: Discussion, Duplicate
