### ISSUE TITLE
autoenv: ctr-c exit the shell

### ISSUE THREAD

**Issue by linkit87** [sorin-ionescu/prezto#901] opened 2015-06-10 13:20 UTC
In folder where is a .env file pressing ctr-c cause the shell to exit

**Comment by sorin-ionescu** [comment] 2015-06-10 18:13
Duplicate of #888?

**Comment by linkit87** [comment] 2015-06-11 10:36
Don't know, but I noticed that if I disable 'syntax-highlighting'  and 'history-substring-search'  I don't have the issue. I went back to old sorin version and all it's working fine

**Comment by sorin-ionescu** [comment] 2015-06-11 14:32
Both? Disable only syntax-highlighting.

**Comment by linkit87** [comment] 2015-06-12 08:25
This is my configuration:
```
zstyle ':prezto:load' pmodule \
  'environment' \
  'terminal' \
  'editor' \
  'history' \
  'directory' \
  'spectrum' \
  'utility' \
  'completion' \
  'syntax-highlighting' \
  'history-substring-search' \
  'git' \
  'osx' \
  'prompt' 
```
Issue scenario:

1) both 'syntax-highlighting' and  'history-substring-search' activated
1) removing only 'syntax-highlighting'
2) removing only  'history-substring-search'

Working scenario:

1) without both them
2) with old sorin theme version

**Closed** 2016-03-03 03:27 UTC
Labels: Discussion
