### ISSUE TITLE
after adding module syntax-highlighting, it shows broken pipe.

### ISSUE THREAD

**Issue by funnyEagle** [sorin-ionescu/prezto#1103] opened 2016-03-15 23:21 UTC
adding the module before prompt, and restart iterm2, it shows message ''broke pipe''.

Any idea what happened here?

Thanks a lot.

**Comment by beanaroo** [comment] 2016-04-11 13:15
did you possibly forget to escape the new line? Like so:

```
  'syntax-highlighting' \
  'prompt'
```

**Comment by belak** [comment] 2017-04-07 06:28
Duplicate of #1026

**Closed by belak** 2017-04-07 06:28 UTC
Labels: Discussion, Duplicate
