### ISSUE TITLE
GPG_AGENT_INFO not populated

### ISSUE THREAD

**Issue by danilobuerger** [sorin-ionescu/prezto#1252] opened 2017-02-05 11:56 UTC
When enabling the gpg module the GPG_AGENT_INFO env only gets populated when starting up the gpg-agent. When the gpg-agent is already started, the env doesn't get set.

**Comment by facastagnini** [comment] 2017-03-04 16:00
Hey @danilobuerger  this repo is not being maintained, see #1239

The community fork is here https://github.com/zsh-users/prezto, you may have better luck over there.

zsh-users is an organization dedicated to host Zsh community projects and therefore became the rational home for a community maintained version of prezto.

Please move this issue to zsh-users and we will be able to help you!

**Comment by danilobuerger** [comment] 2017-03-04 16:11
@facastagnini thanks for telling me about this, I didn't even know. It's a shame that he just disappeared and nobody can even change the README...

**Comment by paulmelnikow** [comment] 2017-03-04 16:25
@danilobuerger I ran into the same situation a few months ago. It would be great if we could more easily guide users to the new repo.

If you star it, that helps. Also as we start to build up activity there, perhaps the new fork will start to show up in Google results.

**Comment by danilobuerger** [comment] 2017-03-04 16:29
Awesome, I already made the switch and starred it!

**Comment by facastagnini** [comment] 2017-03-04 17:25
thanks for following us @danilobuerger , once the issue is on the forked project put the reference here and please close this ticket 👍

**Comment by belak** [comment] 2017-11-10 20:24
I've pushed a small change which should fix this issue. If you're still having problems, feel free to ping me or open a new issue.

**Closed by belak** 2017-11-10 20:24 UTC
Labels: Discussion
