### ISSUE TITLE
zsh + tmux  loses history substring search functionality

### ISSUE THREAD

**Issue by esn89** [sorin-ionescu/prezto#1065] opened 2016-01-21 07:58 UTC
noticed that that seems to happen, despite enabling the tmux module.  I have set my $TERM to rxvt-unicode-256color, is there something i am missing out on?

**Comment by sorin-ionescu** [comment] 2016-03-02 02:48
This seems to be a duplicate of #1059.

**Comment by sorin-ionescu** [comment] 2016-03-02 02:49
What does tmux have to do with history-substring-search?

**Closed by sorin-ionescu** 2016-03-02 02:48 UTC
Labels: Discussion, Duplicate

**Comment by Ulu2005** [comment] 2017-05-13 06:10
Met same issue when I have $TERM=screen256-color and "tmux-256color" in tmux default-terminal option. Then resolved this by setting default-terminal in tmux to "screen-256color".

**Comment by neverfox** [comment] 2018-04-01 23:25
> What does tmux have to do with history-substring-search?

Probably issue with terminfo key bindings.
