### ISSUE TITLE
Powerline prompt: Symbols broken

### ISSUE THREAD

**Issue by bax-** [sorin-ionescu/prezto#1072] opened 2016-01-28 09:00 UTC
I have the Powerline Fonts installed, all the other Powerline themes work for me in the OS X Terminal and iTerm2.
But the "Powerline" prompt has broken symbols…

**Comment by andya9** [comment] 2016-02-21 11:42
i can confirm this too

**Comment by sorin-ionescu** [comment] 2016-03-01 20:46
You need to install patched fonts. Read the Powerline README.

**Comment by bax-** [comment] 2016-03-01 20:58
I installed the patched fonts.
All the other prompts using powerline fonts are working, only the powerline prompt isn't.

**Comment by sorin-ionescu** [comment] 2016-03-01 21:05
I don't know.

**Comment by nomoon** [comment] 2016-04-01 01:08
Looks like Powerline changed their codepoints for their fonts at some point between 2012 and now, and the powerline prezto theme is pulling from https://github.com/davidjrice/prezto_powerline, which hasn't been updated since then. There's a PR https://github.com/davidjrice/prezto_powerline/pull/2 that updates these points... maybe it could be pulled into this main repo?

**Comment by sorin-ionescu** [comment] 2016-04-01 14:25
Who is actually maintaining Powerline?

**Comment by toolbear** [comment] 2016-05-01 00:07
I forked [davidjrice/prezto_powerline](https://github.com/toolbear/prezto-powerline) to [toolbear/prezto-powerline](https://github.com/toolbear/prezto-powerline)

* fixed Powerline font code points
* lose generic VCS status; gain detailed git status
* leak fewer globals
* [base16](https://github.com/chriskempson/base16) friendly colors
* detect node and java projects (in addition to ruby)

Currently it depends on changes in [my prezto fork](https://github.com/toolbear/prezto) that I need to clean up and disentangle from my other customizations before I can make a PR. In the meantime you're welcome to try it out if you're willing to run off my fork or cherry-pick the necessary prezto changes.

**Comment by ericbn** [comment] 2016-07-08 00:23
I came here for the same reason @nomoon described. Looks like @davidjrice is not maintaining his [davidjrice/prezto_powerline](https://github.com/davidjrice/prezto_powerline) for the last 4 years, and that is what prezto is referencing.

**Comment by ericbn** [comment] 2016-07-13 17:14
The [davidjrice/prezto_powerline](https://github.com/davidjrice/prezto_powerline) was just updated. Created pull req #1169 to update the subproject commit in prezto.

**Comment by belak** [comment] 2017-04-07 06:27
The external module has been updated so this should be fixed!

If you continue to have problems with this, please open another issue or ask for this one to be reopened.

**Closed by belak** 2017-04-07 06:27 UTC
Labels: Bug, Upstream
