### ISSUE TITLE
Should exec be used in auto-start tmux module?

### ISSUE THREAD

**Issue by ivanvig** [sorin-ionescu/prezto#1599] opened 2018-06-28 20:09 UTC
I was looking the code because I had a strange behavior between yakuake and konsole using tmux auto-start and found that exec is used [here](https://github.com/sorin-ionescu/prezto/blob/master/modules/tmux/init.zsh#L41). That explains why the terminal is closed when detaching #1140 and therefore why opening a new instance of konsole would kill the previous one.

So, it is really needed to use exec?.

**Comment by belak** [comment] 2018-06-28 20:46
I believe the exec was done here on purpose and is a design decision, not a bug.

I would be open to a setting which doesn't use exec, but I don't have any plans to add this in the future.

**Comment by belak** [comment] 2018-09-28 21:30
I'm going to close this for now, since, as mentioned above, I'm fairly sure this was a choice by the package designers to make it easier to run a tmux session (and connect to it automatically) as soon as the shell opens. It would be a slightly weird behavior to attempt to open a tmux session on every terminal load and have a normal shell when dropping out of it.

That being said, I'd welcome a PR which adds an option to do what you're looking for.

**Closed by belak** 2018-09-28 21:30 UTC
