### ISSUE TITLE
Clone of 'https://gist.github.com/3712874.git' into submodule path 'modules/prompt/external/agnoster' failed

### ISSUE THREAD

**Issue by kaluzki** [sorin-ionescu/prezto#1027] opened 2015-11-11 21:33 UTC
git clone --recursive https://github.com/sorin-ionescu/prezto

see https://github.com/sorin-ionescu/prezto/blob/master/.gitmodules#L15

**Comment by felixjung** [comment] 2015-11-11 21:46
Same issue here.

**Comment by Eriner** [comment] 2015-11-11 21:47
dupe of https://github.com/sorin-ionescu/prezto/issues/940

**Closed** 2015-11-11 21:50 UTC
