### ISSUE TITLE
once switched to powerline10k prompt, the prompt command will not switch to any other prompt

### ISSUE THREAD

**Issue by jspv** [sorin-ionescu/prezto#1833] opened 2020-05-08 01:13 UTC
### Description

When using the `prompt powerlevel10k` command to switch to powerlevel10k, I cannot switch to any other prompt.  If I attempt to switch back, the `prompt -c` command will show the newly selected theme, but the prompt will remain powerlevel10k.

### Expected behavior
The prompt should switch to the selected prompt theme.

### Actual behavior
The prompt stays powerline10k

### Steps to Reproduce

1. Select Sorin prompt
`prompt sorin`

2. Select Powerline10k prompt
`prompt powerlevel10k`

3. Select Sorin prompt again
`prompt sorin`

### Versions

  - Prezto commit:
commit 13c61bae30c3a8cf610623c094f2aa0a95fbf035 (HEAD -> master, origin/master, origin/HEAD)
Author: Amyn <amynbe@gmail.com>
Date:   Sat May 2 19:21:27 2020 +0100

  - ZSH version:
zsh 5.7.1 (x86_64-apple-darwin19.0)
zsh 5.4.2 (x86_64-ubuntu-linux-gnu)

  - OS information:
MacOS 10.15.4
Ubuntu 18.04

**Comment by srijanshetty** [comment] 2020-05-14 08:39
The repro works and I found the same regression as well.

**Comment by belak** [comment] 2020-05-27 23:35
I don't know if there's a great way around this - many prompts set a bunch of additional variables and settings... and add hooks. Because zsh doesn't really provide a way to clean this up after a prompt is set, most complex prompts are set-once.

**Comment by srijanshetty** [comment] 2020-05-28 08:10
@belak: that's what I thought, it was as plain vanilla as clearing the prompt. 

@jspv: closing this issue as of now because there isn't a straighforward way to fix this regression.

**Closed by srijanshetty** 2020-05-28 08:10 UTC

**Comment by romkatv** [comment] 2020-07-06 16:00
> @jspv: closing this issue as of now because there isn't a straighforward way to fix this regression.

What do you mean by regression? Has it ever worked?

You can unload powerlevel10k with this command:

```zsh
powerlevel10k_plugin_unload
```

In general you should expect that themes cannot be unloaded. E.g., `sorin` cannot be unloaded.

**Comment by srijanshetty** [comment] 2020-07-07 10:54
@romkatv my bad with calling it a regression. What I meant to convery was prompt loading usually has side-effects and there's no straightforward way to contain and revert side-effects.

**Comment by romkatv** [comment] 2020-07-07 11:53
I didn't know that `prompt_cleanup` existed. It doesn't work as you've pointed out. I sent https://www.zsh.org/mla/workers//2020/msg01021.html with a patch. If it gets accepted (or some other fix along those lines is applied), I'll add a call to `prompt_cleanup` in Powerlevel10k.

**Comment by srijanshetty** [comment] 2020-07-08 10:05
Thanks a lot for your contributions @romkatv
