### ISSUE TITLE
Override prompt coloring 

### ISSUE THREAD

**Issue by jeeftor** [sorin-ionescu/prezto#1422] opened 2017-08-08 00:33 UTC
Just getting my head wrapped around how zsh works.  If i wanted to change the prompt color of an item is there a way to do this?

I know that say in `sorin` the colors are set in the `prompt_sorin_setup` file

```
  zstyle ':prezto:module:git:info:commit' format ' %%B%F{3}%.7c%f%%b'
  zstyle ':prezto:module:git:info:deleted' format ' %%B%F{1}✖%f%%b'
  zstyle ':prezto:module:git:info:modified' format ' %%B%F{4}✱%f%%b'
  zstyle ':prezto:module:git:info:position' format ' %%B%F{13}%p%f%%b'
  zstyle ':prezto:module:git:info:renamed' format ' %%B%F{5}➜%f%%b'
  zstyle ':prezto:module:git:info:stashed' format ' %%B%F{6}✭%f%%b'
  zstyle ':prezto:module:git:info:unmerged' format ' %%B%F{3}═%f%%b'
  zstyle ':prezto:module:git:info:untracked' format ' %%B%F{7}◼%f%%b'
```

If i want to change these files can i put a redefinition command somewhere or do i have to edit the `prompt_sorin_setup` file directly?

**Comment by johnpneumann** [comment] 2017-08-10 08:47
Some of this is already outlined in the [prompt](https://github.com/sorin-ionescu/prezto/tree/master/modules/prompt) readme, however, some additional information may be helpful here.

Create a directory for your modified theme `mkdir ${HOME}/.zsh_prompts` and then save the current sorin theme to that folder with a new name (eg. `prompt_jeeftors_awesome_sorin_setup`). Modify it to your hearts content.

In your `.zshrc` after it says `# Customize to your needs...`

```
autoload promptinit
fpath=(${HOME}/.zsh_prompts $fpath)
promptinit

prompt 'prompt_jeeftors_awesome_sorin_setup'
```

**Comment by jeeftor** [comment] 2017-08-10 12:37
Ok so the answer is to modify an existing prompt - which means if say the sorin prompt gets updated - my custom prompt is now out of date.  Correct?

**Comment by belak** [comment] 2017-08-10 20:16
Yes, unfortunately. There are a few prompts which ship with zsh where you can change the colors, but I'm not sure if we have any plans to support that in many prompts here.

**Comment by johnpneumann** [comment] 2017-08-10 22:53
If you do what I suggested, no. You copy it as your own theme and put it in
the location stated and it will function without the need for you to do
anything else with the base sorin version. It only needs to be named
differently on the filesystem as that's how themes are pulled up when
running any of the prompt commands.

**Comment by belak** [comment] 2017-08-10 23:00
Right, the prompt will still work, but it won't get any of the changes from the original prompt.

**Comment by johnpneumann** [comment] 2017-08-16 08:16
Correct, you'll just get what you get and generate a patch each time there's an update and apply it (modifying the colors based on that).

**Comment by johnpneumann** [comment] 2017-08-16 08:17
If this answers your question, please close the issue. If it doesn't, then let us know what else you need to be able to close it.

**Comment by belak** [comment] 2017-08-16 18:34
Additionally, specifically for the sorin prompt, if you modify those git definitions after the prompt is set, it should work.

**Closed** 2017-08-16 20:39 UTC
Labels: Documentation

**Comment by jeffwidman** [comment] 2017-08-16 20:40
> If this answers your question, please close the issue. If it doesn't, then let us know what else you need to be able to close it.

I think it's better to default close when a maintainer thinks the issue is resolved, with a note that we're happy to re-open if still needed. For several other large projects that I'm involved with, this saves a lot of time and makes life much easier.

**Comment by belak** [comment] 2017-08-16 20:45
Yep, I even ask them to open a new issue sometimes as it's easy for a comment on a closed issue to get lost. :)

**Comment by johnpneumann** [comment] 2017-08-16 23:08
Treading softly after the last few days, but agree I should have closed it.
Thanks gents.
