### ISSUE TITLE
Extra else in secondary prompt

### ISSUE THREAD

**Issue by jgdye** [sorin-ionescu/prezto#1415] opened 2017-08-04 16:13 UTC
### Description
When showing the secondary prompt during an if, else, etc., there is always an extra else in the prompt

### Expected behavior

Only the commands actually entered should be listed

### Actual behavior

![image](https://user-images.githubusercontent.com/4614540/28977032-66126822-790e-11e7-87d5-a7db5901bc5c.png)

This happened after updating a rather old install (based on 4f19700) that didn't show this property, but also occured on a brand new install with a brand new user (Image is from new user)

### Steps to Reproduce

1. Clone repo and install
2. Input `"` (or other item that will create a secondary prompt and hit return
### Versions

  - Prezto commit: 7b5196c
  - ZSH version: 5.1.1 (Ubuntu) and  5.3.1 (Raspbian)
  - OS information: Ubuntu 16.04 and Raspbian 9

**Comment by indrajitr** [comment] 2017-08-04 17:21
1. What's the output of `print $PROMPT2`?
2. What prompt theme are you using?

I am not sure if we set secondary prompt in default theme viz., _prompt_sorin_theme_ (which would be the case with brand new setup). Is it possible that you have a different source (~/.zshrc, ~/.zprofile, /etc/zprofile etc.) which is bringing this in?

**Comment by belak** [comment] 2017-08-04 17:54
I just tried this on Ubuntu 16.04 with ZSH 5.1.1 and wasn't able to reproduce it. Do you have your dotfiles anywhere public so we can test this? Or is it just your prezto fork?

**Comment by indrajitr** [comment] 2017-08-04 19:13
@jgdye, just looked at your prezto fork.

1. Is it possible that you are using [joshua theme](https://github.com/jgdye/prezto/blob/master/runcoms/zpreztorc#L95)?
2. The theme seems to be [customizing `PS2`](https://github.com/jgdye/prezto/blob/8557ed5e99eeb739d9afdc14a42ba218642be811/modules/prompt/functions/prompt_joshua_setup#L140-L143).

I am closing this based on the assumption that you are using custom theme (joshua) which has `PS2` customization _outside_ what prezto provides. Please feel encouraged to re-open if you consider my assumption incorrect and/or you mange to find some other prezto issue.

**Comment by jgdye** [comment] 2017-08-05 00:32
This occurs on a clone of the primary repository installed in a fresh user using the sorin prompt with a $PS2 value of `%_>`. I'm away from the system at the moment and can only ssh in with my phone, so my troubleshooting capability is somewhat limited, but a `git bisect` shows the issue arose with b38ced8. When I can get on the system later this weekend I'll try a complete reinstall of zsh and prezto to verify nothing unusual being sourced followed by removing the changes in that commit if the reinstall doesn't fix the issue.On Aug 4, 2017 3:13 PM, Indrajit Raychaudhuri <notifications@github.com> wrote:Closed #1415.

**Comment by indrajitr** [comment] 2017-08-05 05:35
Aha, so #1272 is the one behind b38ced8. Thanks @jgdye for the analysis.
Looks like we'll need to troubleshoot this.

/cc @johnpneumann

**Comment by jgdye** [comment] 2017-08-05 12:19
After testing on a minimal Ubuntu VM, the issue is present. Using an SSH connection it occurs out of the box, using the console you have to explicitly set PS2 to include %_.  Setting ps-context to yes appears to resolve the issue on a default install, but that's with fairly minimal testing.

**Comment by johnpneumann** [comment] 2017-08-05 14:41
Looking at this now. It's strange that this is just now occurring after being in use for months.

**Comment by johnpneumann** [comment] 2017-08-08 08:19
I've attempted to reproduce this issue on 3 separate machines with no luck. Default install with nothing added. 

Docker Attempt:

```Dockerfile
FROM ubuntu:xenial

RUN apt-get update && apt-get -y upgrade
RUN apt-get -y install sudo build-essential curl vim git zsh python python-dev ruby

WORKDIR /tmp

RUN curl -L -O https://bootstrap.pypa.io/get-pip.py
RUN python get-pip.py
RUN pip install --upgrade pip setuptools requests
RUN rm get-pip.py

RUN useradd -ms /bin/zsh zshuser
RUN usermod -aG sudo zshuser
RUN chsh -s /bin/zsh zshuser

USER zshuser
RUN cd && git clone --recursive https://github.com/sorin-ionescu/prezto.git "${ZDOTDIR:-$HOME}/.zprezto"
ADD prezto_setup.sh prezto_setup.sh
RUN /bin/zsh prezto_setup.sh

WORKDIR /home/zshuser
ENTRYPOINT /bin/zsh
```

Corresponding prezto_setup.sh script:
```prezto_setup.sh
#!/bin/zsh
setopt EXTENDED_GLOB
for rcfile in "${ZDOTDIR:-$HOME}"/.zprezto/runcoms/^README.md(.N); do
    ln -s "$rcfile" "${ZDOTDIR:-$HOME}/.${rcfile:t}"
done
```

Run it with:
```bash
docker run --rm -it zsh-ubuntu-xenial
````

Vagrantfile:

```Vagrantfile
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"

  config.vm.provision "file", source: "dockerfiles/ubuntu/prezto_setup.sh", destination: "prezto_setup.sh"

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get -y upgrade
    apt-get -y install sudo build-essential curl vim git zsh python python-dev ruby
    cd /tmp
    curl -L -O https://bootstrap.pypa.io/get-pip.py
    python get-pip.py
    pip install --upgrade pip setuptools requests
    rm get-pip.py

    cd /home/ubuntu
    chsh -s /bin/zsh ubuntu
    export ZDOTDIR=$(pwd)
    git clone --recursive https://github.com/sorin-ionescu/prezto.git "${ZDOTDIR:-$HOME}/.zprezto"
    /bin/zsh ./prezto_setup.sh

  SHELL
end
```

I used the same corresponding script from above in this setup as well. Now run:

```bash
vagrant up
vagrant ssh
```

I also stood up a new remote machine on DO and tried the same things as listed above and couldn't get this issue to pop up. 

I attempted multiple permutations of the issue, attempting to make it fail, but could not. Since no one can reproduce this, I'm closing it. If someone else can reproduce the behaviour, I'm more than happy to take another look at this.

**Closed by johnpneumann** 2017-08-08 08:19 UTC
