### ISSUE TITLE
Python module causes [Process Completed] 

### ISSUE THREAD

**Issue by amir20** [sorin-ionescu/prezto#918] opened 2015-07-08 20:39 UTC
I have spent hours debugging this and I was able to finally find what caused the following error. 

<img width="1145" alt="screen shot 2015-07-08 at 1 34 52 pm" src="https://cloud.githubusercontent.com/assets/260667/8581558/684afa8e-2576-11e5-9eb6-064356e75b7b.png">

My enabled modules are: 

```
zstyle ':prezto:load' pmodule \
  'environment' \
  'terminal' \
  'editor' \
  'history' \
  'directory' \
  'spectrum' \
  'utility' \
  'ssh' \
  'completion' \
  'homebrew' \
  'osx' \
  'ruby' \
  'rails' \
  'git' \
  'syntax-highlighting' \
  'history-substring-search' \
  'python' \
  'prompt'
```

It seems like `virtualenvwrapper` is causing the problem. If I remote the following block then I do not see the error anymore...

```
if (( $+commands[virtualenvwrapper.sh] )); then
  # Set the directory where virtual environments are stored.
  export WORKON_HOME="$HOME/.virtualenvs"

  # Disable the virtualenv prompt.
  VIRTUAL_ENV_DISABLE_PROMPT=1

  source "$commands[virtualenvwrapper.sh]"
fi
```

I had `virtualenvwrapper` installed but even after removing it, I still have this problem. 

```
brew ls | grep py                                                                                                                
pyenv
python3
```

What other detail can I provide? I am afraid I don't know enough about python to help any further.

**Comment by sorin-ionescu** [comment] 2015-07-09 00:08
Duplicate of #898.

**Closed by sorin-ionescu** 2015-07-09 00:08 UTC
Labels: Duplicate
