### ISSUE TITLE
Unexpected global alias execution caused by fasd

### ISSUE THREAD

**Issue by hghwng** [sorin-ionescu/prezto#1326] opened 2017-06-02 09:32 UTC
### Description

I tried to alias `sponge` as `SP` in zsh. But the result is pretty surprising.

Without global alias:

```
❯ echo xxx >! xxx
❯ cat xxx | sponge xxx
❯ cat xxx  # non-empty file
xxx
```

With global alias:

```
❯ echo xxx >! xxx
❯ alias -g SP='| sponge '
❯ cat xxx SP xxx
❯ cat xxx
(empty file, no lines are shown here)
```

The snippet with global alias also works in **stock** zsh.

**UPDATE**: After disabling fasd the alias executes as expected. 

### Versions

  - Prezto commit: 7ae7a02
  - ZSH version: zsh 5.3.1 (x86_64-unknown-linux-gnu)
  - OS information: Arch Linux

**Comment by belak** [comment] 2017-06-02 17:08
I'm not really sure what you're running into here. The above snippet worked for me (macOS, zsh 5.3.1)... and it even worked when I cloned your fork (I believe you set it automatically in there). Do you have any additional information you can provide that would make it possible to reproduce this?

**Comment by hghwng** [comment] 2017-06-05 10:56
I found the culprit! After disabling the `fasd` plugin, the alias works now!

However, I'm not sure whether it's fasd itself that breaks the alias, or it's the plugin part of prezto.

**Comment by hghwng** [comment] 2017-06-05 11:17
@belak Thank you for your thorough investigation! I neglected that I was using a fork when doing the test.

Today I tried to use stock prezto, only adding `fasd` to `zpreztorc`. The alias still won't work in this configuration.

**Comment by belak** [comment] 2017-06-19 08:21
SP is not used anywhere in prezto or fasd as far as I can tell, so I don't know what to tell you.

Note that you can use the `alias` command without arguments to see all aliases currently defined (or `alias -g` to see all global aliases) which may make this easier to track down.

**Comment by jeffwidman** [comment] 2017-08-16 17:27
I'm going to close this for now as unable to reproduce. Happy to re-open if you can provide instructions to repro.

**Closed by jeffwidman** 2017-08-16 17:27 UTC
