### ISSUE TITLE
Do not use rm's -i options by default

### ISSUE THREAD

**Issue by ghost** [sorin-ionescu/prezto#205] opened 2012-06-19 18:31 UTC
I don't think that it is a good idea to [alias](https://github.com/sorin-ionescu/oh-my-zsh/blob/master/modules/utility/init.zsh#L53) `rm` to `rm -i` by default, because it is annoying and therefore users will just enter `y` without reading the name of the prompted file, or they will just start using the -f options. 
I personally think that this is very counterproductive.

**Comment by herrbischoff** [comment] 2015-10-21 17:55
Also, sorry to to necro-post but I just switched to prezto and this default is the single biggest annoyance I found with it. Also, due to its rather thin documentation, it took me a while to find this issue. Just wanted to comment on it.

**Comment by sorin-ionescu** [comment] 2015-10-24 17:00
I am inclined to keep it. I shot myself too many times in the foot. There is not a big protest against it.

**Comment by herrbischoff** [comment] 2015-10-24 18:39
Well, no problem. I managed to find it eventually. Apparently there are more people out there that need to be safeguarded from their own actions than I thought... ;P

**Comment by mateogianolio** [comment] 2016-03-15 12:49
I was also really annoyed that it's like this by default.

**Comment by joaquinlpereyra** [comment] 2016-03-29 17:01
+1 to disabling it by default or at least make it obviously configurable in the settings somewhere, as some plugins are in the .zprestorc file.

**Comment by excetara2** [comment] 2016-04-15 06:15
Y+1 disable or making obvious the default. I was confused by this for awhile as well. At least state it somewhere obvious because I couldn't figure out why it kept prompting me when typing rm without the -i.

**Comment by sorin-ionescu** [comment] 2016-04-16 01:35
It stays. Don't be [this guy](http://www.independent.co.uk/life-style/gadgets-and-tech/news/man-accidentally-deletes-his-entire-company-with-one-line-of-bad-code-a6984256.html).

**Comment by joaquinlpereyra** [comment] 2016-04-16 13:16
@sorin-ionescu There are saner settings available to avoid that. For example, warn if user tries to rm -rf any folder not in his home. Besides, this settings would do anything against rm -rf, the *force* would do it anyway. 

If you feel so strongly about it (which is a matter of personal taste, can't be discussed and, after all, you're the project's owner), I'd recommend at least documenting it clearly somewhere in the settings. Less intrusive things are stated there.

**Comment by sorin-ionescu** [comment] 2016-04-16 16:07
Asking for confirmation is good user experience.

**Comment by mateogianolio** [comment] 2016-04-16 16:12
Changing the default behaviour of a common bash function without mentioning
how to reverse it is bad user experience. However, it is of course entirely
your decision as project owner.

**Comment by sorin-ionescu** [comment] 2016-04-21 00:56
I didn't think it needs documenting since you notice it the first time you try it. Why is it working differently? Just check the alias.

```zsh
$ alias rm
rm='nocorrect rm -i'
```

**Comment by jedmund** [comment] 2016-05-04 11:24
It took me months of being more irritated than usual before I realized what zprezto was doing here, and I'm still trying to find a sane way to turn it off. There's no question that there should be a setting and/or documentation alerting the user that this is going to happen.

**Comment by joaquinlpereyra** [comment] 2016-05-04 12:19
@jedmund putting 'unalias rm' in your .zpreztorc should work, btw. best fix I've got right now.

**Comment by andrewramsay** [comment] 2016-05-05 09:08
Was just trying to copy a directory of files over an existing directory ("cp -vfr dir1 dir2") and didn't understand at first why I was still getting "Overwrite y/n?" prompts for **every single file** despite the "-f". 

These aliases should absolutely be disabled by default. If you find yourself deleting or overwriting files you didn't mean to all the time, you're entirely free to enable them on your own. Please don't push it on everyone else just because you think it's better to be (extremely) safe than sorry. This "feature" produces unexpected behaviour from a basic system tool and that is **never** a good idea IMO. I imagine it's certainly going to cause problems for anyone that uses cp -f in a shell script and finds it waiting for user input... same thing for rm, which has also been annoying me with these prompts.

**Comment by jedmund** [comment] 2016-05-05 09:11
@joaquinlpereyra Thanks! Thats more elegant than what I was doing, which was just re-aliasing to the regular command with a space.

**Comment by mateogianolio** [comment] 2016-05-12 13:05
@joaquinlpereyra not sure how my config differs (OSX), but I had to put the `unalias` commands in `.zshrc` because putting them in `.zpreztorc` resulted in `no such hash table element: rm`.

**Comment by joaquinlpereyra** [comment] 2016-05-13 15:02
@mateogianolio You're right. I got the name of the file wrong. You should put it in .zshrc :)

**Comment by danielbmarques** [comment] 2016-07-05 06:33
@sorin-ionescu It seems like the main argument for keeping this is to err on the side of caution, but the result is quite the opposite: prezto users will get used to being sloppy and careless and can do serious damage on other computers.

> If you're on a system that doesn't have it, and you rm, it immediately starts deleting and you're wondering what's going on.
>
> Many users are used to SSH'ing into different systems; so using lots of different systems, sometimes without personalized user accounts (including aliases) set up, is rather common.
> 
> Instead, use e.g. `alias rmi='rm -i'` and learn to use that one. If that isn't set up on a different system, you didn't accidentally delete files and can always fall back to typing the full command.

(http://superuser.com/a/384770)

**Comment by sorin-ionescu** [comment] 2017-05-06 19:09
@belak What do yo think of @dbmrq's suggestion?

**Comment by geoelectric** [comment] 2017-05-07 01:21
FWIW, I'm in full agreement that setting the prompt to always fire will train people to ignore it, and also in agreement that it was a bit of an annoyance until I figured out it was a prezto module doing it. When you're new to zsh in general then a framework on top of it, figuring out what does what is hard enough without flipping defaults.

Since it seems you're looking at this again, why not separate out those particular aliases (the ones into a "safeops" type module, and--assuming you still feel strongly--load it by default right after utility? 

That seems like a straightforward step towards making it both more obvious and configurable for the user without sacrificing any values mentioned and probably easier than implementing a flag.

**Comment by jeeftor** [comment] 2017-06-21 00:40
I'd like to pipe in and say the `rm` thing was driving me crazy.  I'd really like to see a more elegant way of handling it.

**Comment by belak** [comment] 2017-06-21 19:53
Thanks to everyone for weighing in! Sorry it's taken me so long to get to this.

I'm not really sure what I want to do with this. On one hand, it forms bad habits (people often resort to adding -f to ignore the prompt which is very bad) and can end up relying on it... so when it isn't there it causes problems... But on the other hand, people who *are* legitimately using this shouldn't expect it to disappear from under their feet. Especially because the current proposal asks to disable a prompt that confirms you want to delete files.

So, here are my suggestions:

* Add the `*i` aliases suggested by @dbmrq above
* Add a `safeops` option or something similar which will add `-i` to the above commands (not sure if this should default on or off... my current opinion is that we shouldn't change the default behavior)

I have mixed opinions on changing the default behavior for something that could potentially cause data loss for people who are using the same commands, but I'm still open to being convinced on that.

**Comment by gpanders** [comment] 2017-06-22 14:38
Not sure if all versions of `rm` have this option, but with standard GNU `rm` on Ubuntu 16.04, there is a `-I` flag (capital i) that will "prompt one when removing more than three files, or when removing recursively". If the `-i` flag _must_ be a default, might I suggest using this option instead? That way, removing one file will not bug the user, but trying to remove an entire directory will, and even then it only asks once (instead of asking about every single file in the directory).

**Comment by belak** [comment] 2017-06-22 17:34
I like that @gpanders but I don't think OSX or BSD support that option.

**Comment by dbmrq** [comment] 2017-06-24 00:41
@belak 
> I have mixed opinions on changing the default behavior for something that could potentially cause data loss for people who are using the same commands

So you have to chose between potentially causing data loss for the limited number of people who already use Prezto or potentially causing data loss for the unlimited number of people who may still use Prezto in the future. I think the first option is better.

I agree that this shouldn't disappear from under people's feet, though. [Traditionally I guess this would be fixed with the release of a new major version](http://semver.org), so people who were upgrading to Prezto 2.0.0 would know there are breaking changes and look into them before upgrading. Prezto doesn't seem to use any kind of versioning though.

**Comment by belak** [comment] 2017-07-11 18:54
This has been resolved by #1375 and aad91beb3c60bab04a09a10fa56c56b469251cd3.

A new option has been added by @samcv which allows you to disable safe-ops by default. There have also been a new set of aliases added (rmi, lni, etc) which are explicit about what they do.

Thanks to everyone for your feedback!

**Closed by belak** 2017-07-11 18:54 UTC
Labels: Discussion, Idea

**Comment by philihp** [comment] 2022-02-02 00:18
I wish zprezto asked me for confirmation before redefining `rm` to ask for confirmation.
