### ISSUE TITLE
Can there be a way to have `pmodload` look for modules somewhere other than `ZDOTDIR`/`HOME`?

### ISSUE THREAD

**Issue by gwerbin** [sorin-ionescu/prezto#920] opened 2015-07-09 14:50 UTC
It would be nice to be able to be able to store modules in places other than `~/.zprezto/`, or better yet to store the entire `.zprezto` folder somewhere else, and maybe even give it a different name.

Right now the tree _must_ look like this:

    ~
    |-- .zshrc
    |-- .zpreztorc
    |-- .zprezto
        |-- modules
            |-- helper
            |-- git

It would be nice if I could configure Prezto to use this instead:

    ~
    |-- .zshrc
    |-- .zpreztorc

    /usr/local
    |-- prezto
        |-- modules
            |-- helper
            |-- git

or even

    ~
    |-- .zshrc
    |-- .zpreztorc
    |-- .antigen
        |-- https-COLON--SLASH--SLASH-github.com-SLASH-sorin-ionescu-SLASH-prezto.git
            |-- modules
                |-- helper
                |-- git

I think this would be a good feature for a few reasons:

1. You could store all of the machinery inside `/usr/local/prezto` or something like that, leaving the home directory _solely_ for configuration files.
2. It would make it easier for users to write their own modules without forking the entire Prezto project.
3. It would allow users of programs like Antigen to isolate sections of Prezto. Right now Antigen is getting `pmodload` to work from inside its own `.antigen` directory by permanently changing `ZDOTDIR`. See zsh-users/antigen/issues/137

**Comment by sorin-ionescu** [comment] 2015-07-09 20:42
Duplicate of #761, #271.

**Closed by sorin-ionescu** 2015-07-09 20:42 UTC
Labels: Duplicate, Revision
