### ISSUE TITLE
unpredictable zombie sessions

### ISSUE THREAD

**Issue by twork** [sorin-ionescu/prezto#1024] opened 2015-11-11 02:52 UTC
Since installing zprezto (and maybe during the brief time when I had oh-my-zsh going, not sure), every once in a while my shell will conclude a command, and zombie.

I know this isn't much to go on. But I haven't been able to narrow it down much more than that. I've had this happen on both OSX and Linux (Debian), local sessions and inside screen+ssh, in both xterm and gnome-terminal... About half a dozen times today.

The only pattern I can think of is that this seems to happen when I'm typing in a hurry, and I might stumble across an extra key or something. But even if that's the cause I doubt that I'd be the only one experiencing this... I must have something else going on.

Any magical insight? Failing that, clues for how to get better information than just "it stops typing sometimes"?

**Comment by sorin-ionescu** [comment] 2015-11-11 16:38
Duplicate of #888.

**Closed by sorin-ionescu** 2015-11-11 16:38 UTC
