### ISSUE TITLE
Zsh coredump when enabling the layer of "syntax-highlighting"

### ISSUE THREAD

**Issue by liangwang** [sorin-ionescu/prezto#1135] opened 2016-04-23 19:07 UTC
When adding 'syntax-highlighting'  into zpreztorc as the second last item in "pmodule", any new zsh session will crash with segmentation fault as follows:

segmentation fault (core dumped)  zsh

**Comment by sorin-ionescu** [comment] 2016-04-23 22:27
Update your Zsh.

**Comment by liangwang** [comment] 2016-04-24 02:53
My current version is 5.0.1, what is the minimum version for Zsh?

**Comment by liangwang** [comment] 2016-04-26 14:24
@sorin-ionescu , I just tried on another box with MacOS, the zsh is the latest at v5.2, and experienced the same crash after I enable `syntax-highlighting` in `$HOME/.zpreztorc`. Any comments or suggestions are welcomed!

**Comment by malikoth** [comment] 2016-05-17 19:24
I'm getting this too.  It's driving me nuts!  If I already have a zsh session, I can add 'syntax-highlighting' to my .zpreztorc file, then source ~/.zshrc again and then syntax highlighting works perfectly.  But any new session just silently dies.  (I don't even see the seg fault message that liangwang reported)  I have no idea how to identify the cause of this, but I can tell you I'm not using the zsh autosuggestion module (which seems to be the only other known cause of a zsh crash is coming from right now)

**Comment by liangwang** [comment] 2016-05-17 19:51
@malikoth, if zsh is your default shell, then you probably will see nothing as new session silently dies. If you start with another shell (e.g. bash), then launch zsh within that shell, you will see the zsh terminated with the message I posted. 

As @sorin-ionescu suggested, this issue may be related to the zsh version. I tested on three systems: ubuntu 14.04 (zsh 5.0.x), Mac (zsh 5.2.x), ubuntu 16.04 (zsh 5.3.x). The first two systems experience the crash issues, and the last one does not.

**Comment by MarloweW** [comment] 2016-06-18 11:56
Same issue on Mac zsh 5.2

**Comment by rvmlr** [comment] 2016-12-26 13:04
Issue happening on zsh 
==> Pouring zsh-5.3.1.yosemite.bottle.tar.gz

**Comment by Jim-Zenn** [comment] 2017-08-12 22:14
Same issue on android termux

**Comment by belak** [comment] 2017-11-14 03:35
Can anyone here still reproduce this? I'm not seeing it on macOS High Sierra with zsh 5.4.2.

**Comment by malikoth** [comment] 2017-11-14 08:21
Nope.  I've had `syntax-highlighting` on for ... between 6 and 12 months maybe?  I think I just tried putting it back in my `.zpreztorc` file because I really wanted it to work one day, and it did.  🤷‍♂️

**Comment by belak** [comment] 2017-11-14 08:23
Well, that's good to hear! Thanks for responding. I'm going to close this for now. If anyone's still running into this, please file a new issue so we can start debugging again.

**Closed by belak** 2017-11-14 08:23 UTC
Labels: Discussion
