### ISSUE TITLE
Clean Install and Post Install Errors

### ISSUE THREAD

**Issue by dephora** [sorin-ionescu/prezto#1427] opened 2017-08-10 22:56 UTC
### Description
After upgrading zsh to 5.4.1 I started experiencing errors so blew everything related to Prezto away and did a clean install (following the install instructions).

During the install, the only issue was with the autosuggestion commit being invalid so that failed.
`error: no such remote ref de795f7dd92382a8489bd355e1d1e648ecb4ad37
Fetched in submodule path 'modules/autosuggestions/external', but it did not contain de795f7dd92382a8489bd355e1d1e648ecb4ad37. Direct fetching of that commit failed.`
### Expected behavior
No errors.

### Actual behavior
```
Couldn't read file /Users/matt/.zprezto/modules/prompt/functions/prompt_agnoster_setup containing theme agnoster.
Couldn't read file /Users/matt/.zprezto/modules/prompt/functions/prompt_powerline_setup containing theme powerline.
Couldn't read file /Users/matt/.zprezto/modules/prompt/functions/prompt_pure_setup containing theme pure.

prompt_sorin_setup:9: async: function definition file not found

prompt_sorin_setup:39: command not found: async_start_worker

prompt_sorin_setup:40: command not found: async_register_callback

prompt_sorin_precmd:8: command not found: async_flush_jobs                               

prompt_sorin_precmd:21: command not found: async_job
```

I see from the latest commit and #1423 that those prompts throwing errors are in progress,
 however the prompt/external/async is empty after the install resulting in the errors above. 

After pulling it down manually from https://github.com/mafredri/zsh-async/tree/28c7a644227a5ad7249193525ef27734781f6a63, the async errors are resolved.

### Steps to Reproduce

1. Delete everything Prezto
2. Follow install guide on main page.
3. ...

### Versions

  - Prezto commit: 24e5e49ff299dab1e3f854c89009270fc8580e5c (master)
  - ZSH version:  5.4.1
  - OS information: Sierra 10.12.6

**Comment by neysofu** [comment] 2017-08-10 23:19
I am able to reproduce this issue.

**Comment by belak** [comment] 2017-08-10 23:24
This was a mistake caused by 24e5e49ff299dab1e3f854c89009270fc8580e5c where a number of submodules got updated to in-progress hashes which only exist in my repos. I've reverted that commit and correctly re-applied the patch, so everything should be fixed now.

Sorry for the inconvenience.

**Closed by belak** 2017-08-10 23:24 UTC

**Comment by dephora** [comment] 2017-08-10 23:36
Thanks for the quick response!

**Comment by abelsromero** [comment] 2018-08-28 08:16
I just did a clean install on Msys2 and I reproduced the issue. Any workarround?

**Comment by ezintz** [comment] 2018-09-01 08:28
I guess you could try running `git submodule sync --recursive`. For me everything works as expected but I also have to admit that I am using a slightly different installation routine.

**Comment by ezintz** [comment] 2018-09-02 05:56
It seems like the submodule `async` is not initialized, even if it is going to be synchronized. You can also try to run the update command from the Readme, e.g. `git submodule update --init --recursive` for the whole repository or that specific path `~/.zprezto/modules/prompt/external/async`. You can also check before if it already exists: `ls -la ~/.zprezto/modules/prompt/external`.

**Comment by abelsromero** [comment] 2018-09-04 07:16
All files are there.
I could fix `async` initialitzation replacing the path in `functions\async` with a relative path to my home.
But even with that I get this when opening a shell.

```
prompt_sorin_async_tasks:4: command not found: async_start_worker
prompt_sorin_async_tasks:5: command not found: async_register_callback
prompt_sorin_async_tasks:10: command not found: async_flush_jobs
prompt_sorin_async_tasks:13: command not found: async_job
```

I added a couple of "echo" (before & after) commands arround `async_start_work` and apparently it is being processed before sorin, but it still complains the method does not exists. This is what I see.

```
before
after
prompt_sorin_async_tasks:4: command not found: async_start_worker
prompt_sorin_async_tasks:5: command not found: async_register_callback
prompt_sorin_async_tasks:10: command not found: async_flush_jobs
prompt_sorin_async_tasks:13: command not found: async_job
```

Thanks a lot for your time, but it could be some bug in Msys implementation, so maybe is time to give up.

**Comment by jbsolomon** [comment] 2021-02-06 20:13
I am also affected by this (zsh 5.8 running in Git Bash on Windows.)
