### ISSUE TITLE
Setting $(TMPDIR) in zprofile breaks emacsclient in Ubuntu 16.04

### ISSUE THREAD

**Issue by accelas** [sorin-ionescu/prezto#1206] opened 2016-10-07 22:13 UTC
When starting emacs in server mode, it would create a socket file in  `$(TMPDIR)/emacs$(UID)/server`. If `$(TMPDIR)` isn't defined at all, it fallback to `/tmp/emacs$(UID)/server`. In `~/.zprofile`, prezto set `$(TMPDIR)` to `/tmp/$(LOGNAME)`. Since it's `~/.zprofile`, it only applies to interactive shell. 

In Ubuntu 16.04, if you launch emacs by clicking desktop icon, it appears that it won't be getting a `$(TMPDIR)`. So it fallback to the one with "/tmp/" prefix. Once the emacs is launched, and now I want to connect it with emacsclient in a terminal, the emacsclient would fail to find the socket file. This is because the terminal would have `$(TMPDIR)` defined, and the emacsclient would try search the socket file in `/tmp/$(LOGNAME)/emacs$(UID)/server`.

**Comment by facastagnini** [comment] 2016-12-29 04:33
This is basically a duplicate of #1199, which have been merged in the presto community fork.

prezto found a new home at https://github.com/zsh-users/prezto

zsh-users is an organization dedicated to host Zsh community projects and therefore became the rational home for a community maintained version of prezto.

I started merging some PRs, your contribution is greatly appreciated!

**Comment by belak** [comment] 2017-04-05 18:39
The fix was merged yesterday to use mktemp to create temp dirs, so I'm closing this issue now. :)

**Comment by paulmelnikow** [comment] 2017-04-05 21:21
Interesting, I hadn't read this report before. I wonder if this was caused by issue I just mentioned in #1199: that [the test in .zshenv](https://github.com/sorin-ionescu/prezto/blob/master/runcoms/zshenv#L9), which is supposed to load zprofile for non-login shells, doesn't always work.

**Comment by belak** [comment] 2017-04-05 21:22
I misread this issue before so I'm pretty sure it isn't fixed. :/ Sorry about the confusion.

**Comment by belak** [comment] 2017-06-26 22:00
With the fixes which have gone in to TMPDIR this *might* be fixed. Can anyone confirm?

**Comment by avdv** [comment] 2017-07-10 07:13
> With the fixes which have gone in to TMPDIR this might be fixed. Can anyone confirm?

I'm on commit e3520b737f8f6b908e3fc62934ede1a75a16e32b from Jul 7th and this issue is *not* fixed for me. I'm using Arch Linux and also have the problem with Emacs / emacsclient.

This is caused by changes in a4ff6acd563b53e2afd997fd77fef7014619ceb.

**Comment by belak** [comment] 2017-07-10 07:16
Thanks for confirming. Can you post the value of `TMPDIR` to make this a little easier to debug?

**Comment by avdv** [comment] 2017-07-10 07:26
Sure, in Emacs which is started from i3, `TMPDIR` is unset:

```elisp
(getenv "TMPDIR")
nil
```
In an interactive shell, started from i3 it is set to:

```
$ echo $TMPDIR
/tmp/zsh-1000
```

**Comment by belak** [comment] 2017-07-10 07:34
Oh. I feel silly. That makes sense. I guess the fix for that would be to wrap emacs/emacsclient and run it with an unset TMPDIR since we don't have a way to control it elsewhere.

**Comment by avdv** [comment] 2017-07-28 06:53
> Oh. I feel silly. Thanks for posting that. It makes sense. I guess the fix for that would be to wrap emacs/emacsclient and run it with an unset TMPDIR since we don't have a way to control it elsewhere.

Yes, that works. But in my opinion the current behavior is broken. And thus I reverted that change in my fork.

It would work if prezto would not try to set up a special TMPDIR by itself, but just set TMPDIR to `/tmp` as this is the default each program agrees on -- if it really must set it.

**Comment by belak** [comment] 2017-07-28 17:18
I think tmpdir is a leftover from some other lazy practices. I'll see about removing it and/or defaulting it to /tmp soon.

**Closed** 2017-07-28 17:25 UTC
Labels: Bug

**Comment by belak** [comment] 2017-07-28 17:26
This should be good now. Packages will just need to be more careful about whether they need a per-user file (use `$UID`) or a completely unique file (use `mktemp`). I've cleaned up everything I saw to make sure they all continue to work.
