### ISSUE TITLE
Force push on master?

### ISSUE THREAD

**Issue by hotpxl** [sorin-ionescu/prezto#1407] opened 2017-07-26 23:28 UTC
This is the git tree on my side http://imgur.com/97DvuhI

![screenshot](http://i.imgur.com/97DvuhI.png)
Looks like master has diverged and it's really hard to "git pull" to update the repo.

Please use "git revert" instead of a forced push...

**Comment by belak** [comment] 2017-07-26 23:50
We do not use force-push but sorin does prefer rebase and squash over merge-commits which cause this problem. Because he's always encouraged people to maintain their own git repos with tweaks in the past, I'm not sure why, but I haven't bothered with trying to get that changed yet.

**Comment by hotpxl** [comment] 2017-07-27 02:23
i'm not sure rebasing will cause this issue (in fact i prefer rebase over merge as well). just compare df0ecc2 and 8846db9. it looks like (from the commit message) there is a hard reset and force push

**Comment by indrajitr** [comment] 2017-07-27 04:40
@hotpxl, your observation is accurate. This was an accidental force push that shouldn't have happened. I just noticed that my _.git/config_ was messed up (`master` pointing to sorin-ionescu/prezto instead of my personal fork).

Thanks for alerting and my apologies!

**Comment by belak** [comment] 2017-07-27 04:42
My apologies for my assumption then. :)

**Comment by indrajitr** [comment] 2017-07-27 19:12
Closing this, given that we know the root cause.

**Closed by indrajitr** 2017-07-27 19:12 UTC
