### ISSUE TITLE
GPG module output agent already running on NixOS 

### ISSUE THREAD

**Issue by Vonfry** [sorin-ionescu/prezto#1681] opened 2019-01-25 15:02 UTC
### Description
1. On NixOS, gpg don't export `GPG_AGENT_INFO` variable and `S.gpg-agent` file is under `/run/user/<uid>/gnupg/S.gpg-agent`, not `~/.gnupg/`.

2. grep cannot match correctly. 
[prezto-repo about gpg init](https://github.com/sorin-ionescu/prezto/blob/master/modules/gpg/init.zsh#L23)
Because of first point, the second if-condition about grep, cannot match gpg-agent process, but the process exists.

Output `echo ${${${(s.:.)GPG_AGENT_INFO}[2]}:--1} gpg-agent`: `-1 gpg-agent`
Output  `ps -U "$LOGNAME" -o pid,ucomm | grep " gpg-agent` : `29385 gpg-agent`

One way to solve is to use `gpgconf` command I think.

By the way, possibly, there are other system having the same problem. I think we can find another way to decide whether gpg-agent is run or not, or try to fix the second grep regex expression to let it fix all system. 

### Expected behavior
Output: `gpg-agent: a gpg-agent is already running - not starting a new one`

### Actual behavior
No output if it is started.

### Steps to Reproduce
NixOS only.  Reproduce may be done by installing gpg with `nix`.  

### Versions

  - Prezto commit:master
  - OS information: NixOS 18.09

**Comment by Matir** [comment] 2019-10-03 04:54
This also affects Debian testing in the same way.

**Comment by andrei-pavel** [comment] 2019-11-02 15:39
![image](https://user-images.githubusercontent.com/6838492/68073336-a87a7f00-fd97-11e9-8b56-42239de91a61.png)

This fixes it on Arch.

**Comment by 1wilkens** [comment] 2020-05-05 11:59
I think this is a duplicate of #1164 and I proposed a solution there.

**Comment by srijanshetty** [comment] 2020-05-05 14:24
Closing as duplicate of #1164

**Closed by srijanshetty** 2020-05-05 14:24 UTC
